import { TAuditorium } from "../../entities/auditorium/model/interface"
import { Side } from "../../shared/model/geometry"
import { GraphDestination, TGraph } from "../../entities/graph/model/interface"

const leftWing: TAuditorium[] = [
  {
    name: "РИ-401",
    height: 50,
    width: 100,
    coords: { x: 200, y: 0 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-401"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "Лестница",
    height: 70,
    width: 100,
    coords: { x: 350, y: 0 },
    entry: Side.LEFT,
    linkedAuditoriums: [{ floor: 4, id: "Лестница 2 этаж" }],
    neighbors: ["Коридор Лестница", "Коридор РИ-401", "Лестница 2 этаж"],
    floor: 4,
    destination: GraphDestination.LADDER,
    section: "leftWing4",
  },
  {
    name: "РИ-403",
    height: 50,
    width: 100,
    coords: { x: 200, y: 50 },
    entry: Side.RIGHT,
    neighbors: ["Коридор Лестница", "Коридор РИ-403"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-402",
    height: 130,
    width: 100,
    coords: { x: 350, y: 70 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-403", "Коридор РИ-402"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-405",
    height: 100,
    width: 100,
    coords: { x: 200, y: 100 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-402", "Коридор РИ-405"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-404",
    height: 100,
    width: 100,
    coords: { x: 350, y: 200 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-405", "РИ-407", "Коридор РИ-407"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-407",
    height: 100,
    width: 100,
    coords: { x: 200, y: 200 },
    entry: Side.RIGHT,
    neighbors: ["РИ-404", "Коридор РИ-405", "Коридор РИ-407"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-406",
    height: 100,
    width: 100,
    coords: { x: 350, y: 300 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-407", "РИ-409", "Коридор РИ-409"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-409",
    height: 100,
    width: 100,
    coords: { x: 200, y: 300 },
    entry: Side.RIGHT,
    neighbors: ["РИ-406", "Коридор РИ-407", "Коридор РИ-409"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-408",
    height: 100,
    width: 100,
    coords: { x: 350, y: 400 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-411", "Коридор РИ-408"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-411",
    height: 50,
    width: 100,
    coords: { x: 200, y: 400 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-409", "Коридор РИ-411"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-413",
    height: 50,
    width: 100,
    coords: { x: 200, y: 450 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-408", "Коридор РИ-413"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-410",
    height: 50,
    width: 100,
    coords: { x: 350, y: 500 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-413", "Коридор РИ-415", "РИ-415"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-415",
    height: 50,
    width: 100,
    coords: { x: 200, y: 500 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-413", "РИ-410", "Коридор РИ-415"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-417a",
    height: 150,
    width: 100,
    coords: { x: 200, y: 550 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-412", "Коридор РИ-417"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-412",
    height: 100,
    width: 100,
    coords: { x: 350, y: 550 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-415", "Коридор РИ-412"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-414",
    height: 100,
    width: 100,
    coords: { x: 350, y: 650 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-414", "Коридор РИ-417"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-419a",
    height: 150,
    width: 100,
    coords: { x: 200, y: 700 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-414", "Коридор РИ-419"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-416",
    height: 100,
    width: 100,
    coords: { x: 350, y: 750 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-416", "Коридор РИ-419"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-421",
    height: 150,
    width: 100,
    coords: { x: 200, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-421", "Коридор РИ-418"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-418",
    height: 150,
    width: 100,
    coords: { x: 350, y: 850 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-416", "Коридор РИ-418"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-423a",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-420", "Коридор РИ-423", "Тех-помещение"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-425a",
    height: 150,
    width: 100,
    coords: { x: 200, y: 1050 },
    entry: Side.RIGHT,
    neighbors: ["Лестница 2", "Коридор РИ-422", "Коридор РИ-425"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-425а",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1200 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-425", "turnoverLeftToMain"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "Тех-помещение",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1000 },
    entry: Side.LEFT,
    neighbors: ["РИ-423", "Коридор РИ-423", "Коридор РИ-420"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "РИ-422",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-423", "Коридор РИ-422"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing4",
  },
  {
    name: "Лестница 2",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1100 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-422", "РИ-425", "Коридор РИ-425", "Лестница 22"],
    floor: 4,
    destination: GraphDestination.LADDER,
    section: "leftWing4",
  },
]
const mainSection: TAuditorium[] = [
  {
    name: "РИ-417",
    height: 140,
    width: 270,
    coords: { x: 30, y: 1250 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-427а", "Коридор РИ-427"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-419",
    height: 110,
    width: 270,
    coords: { x: 30, y: 1390 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-427", "Коридор РадиоТочка", "turnoverMainToLeft"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-428",
    height: 100,
    width: 70,
    coords: { x: 350, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РадиоТочка", "Коридор РИ-424а"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "С/у",
    height: 100,
    width: 50,
    coords: { x: 420, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор С/у", "Коридор РИ-424а"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "Лестница Слева",
    height: 100,
    width: 120,
    coords: { x: 350, y: 1400 },
    entry: Side.LEFT,
    neighbors: ["Коридор гардероб налево", "Коридор Лестница Слева"],
    floor: 4,
    destination: GraphDestination.LADDER,
    section: "mainSection4",
  },
  {
    name: "РИ-423",
    height: 100,
    width: 160,
    coords: { x: 470, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-425",
    height: 100,
    width: 40,
    coords: { x: 630, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-427",
    height: 100,
    width: 100,
    coords: { x: 670, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-429",
    height: 100,
    width: 55,
    coords: { x: 770, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-431",
    height: 100,
    width: 55,
    coords: { x: 825, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-433",
    height: 100,
    width: 60,
    coords: { x: 880, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-435a",
    height: 100,
    width: 170,
    coords: { x: 940, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-430",
    height: 100,
    width: 200,
    coords: { x: 470, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-424", "Коридор РИ-426"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },

  {
    name: "РИ-432",
    height: 100,
    width: 100,
    coords: { x: 670, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-432", "Коридор РИ-434"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-434",
    height: 100,
    width: 170,
    coords: { x: 770, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-436", "Коридор РИ-438"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "РИ-436",
    height: 100,
    width: 170,
    coords: { x: 940, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-438 направо", "Коридор РИ-438"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection4",
  },
  {
    name: "Лестница Справа",
    height: 100,
    width: 120,
    coords: { x: 1110, y: 1400 },
    entry: Side.RIGHT,
    neighbors: ["Коридор гардероб направо", "Коридор Лестница Справа"],
    floor: 4,
    destination: GraphDestination.LADDER,
    section: "mainSection4",
  },
]

const rightWing: TAuditorium[] = [
  {
    name: "РИ-438а",
    height: 100,
    width: 120,
    coords: { x: 1110, y: 1250 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-438а"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-435",
    height: 150,
    width: 200,
    coords: { x: 1330, y: 1350 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-435"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-437",
    height: 100,
    width: 200,
    coords: { x: 1330, y: 1250 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-438а", "Коридор РИ-437", "Коридор РИ-440"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-440",
    height: 100,
    width: 50,
    coords: { x: 1230, y: 1150 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-442", "Коридор РИ-440", "РИ-439"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-439",
    height: 100,
    width: 50,
    coords: { x: 1330, y: 1150 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-442", "Коридор РИ-440", "РИ-440"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-442",
    height: 50,
    width: 100,
    coords: { x: 1180, y: 1100 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-442", "Коридор РИ-441"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-441",
    height: 100,
    width: 100,
    coords: { x: 1330, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-441", "Коридор РИ-444"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-444",
    height: 100,
    width: 100,
    coords: { x: 1180, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-444", "Коридор РИ-443"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-446",
    height: 150,
    width: 100,
    coords: { x: 1180, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-446", "Коридор РИ-445"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-443",
    height: 150,
    width: 100,
    coords: { x: 1330, y: 900 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-446", "Коридор РИ-443"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
  {
    name: "РИ-445",
    height: 50,
    width: 100,
    coords: { x: 1330, y: 850 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-445"],
    floor: 4,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing4",
  },
]
export const neighborsGraphFourth: TGraph[] = [
  {
    id: "Коридор РИ-401",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-401", "Лестница", "Коридор Лестница"],
    direction: Side.RIGHT,
    points: [325, 25, 325, 35],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор Лестница",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-403", "Лестница", "Коридор РИ-401", "Коридор РИ-403"],
    direction: Side.RIGHT,
    points: [325, 35, 325, 75],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-403",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-402", "РИ-403", "Коридор Лестница", "Коридор РИ-402"],
    direction: Side.RIGHT,
    points: [325, 75, 325, 135],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-402",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-402", "РИ-405", "Коридор РИ-403", "Коридор РИ-405"],
    direction: Side.RIGHT,
    points: [325, 135, 325, 150],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-405",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-404",
      "РИ-405",
      "РИ-407",
      "Коридор РИ-402",
      "Коридор РИ-407",
    ],
    direction: Side.RIGHT,
    points: [325, 150, 325, 250],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-407",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-404",
      "РИ-406",
      "РИ-407",
      "РИ-409",
      "Коридор РИ-405",
      "Коридор РИ-409",
    ],
    direction: Side.RIGHT,
    points: [325, 250, 325, 350],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-409",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-406",
      "РИ-409",
      "РИ-411",
      "Коридор РИ-407",
      "Коридор РИ-411",
    ],
    direction: Side.RIGHT,
    points: [325, 350, 325, 425],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-411",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-411", "РИ-408", "Коридор РИ-409", "Коридор РИ-408"],
    direction: Side.RIGHT,
    points: [325, 425, 325, 450],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-408",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-408", "РИ-413", "Коридор РИ-411", "Коридор РИ-413"],
    direction: Side.RIGHT,
    points: [325, 450, 325, 475],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-413",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-413",
      "РИ-415",
      "РИ-410",
      "Коридор РИ-408",
      "Коридор РИ-415",
    ],
    direction: Side.RIGHT,
    points: [325, 475, 325, 525],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-415",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-410",
      "РИ-415",
      "РИ-412",
      "Коридор РИ-413",
      "Коридор РИ-412",
    ],
    direction: Side.RIGHT,
    points: [325, 525, 325, 600],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-412",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-412", "РИ-417", "Коридор РИ-415", "Коридор РИ-417"],
    direction: Side.RIGHT,
    points: [325, 600, 325, 625],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-417",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-414", "РИ-417", "Коридор РИ-412", "Коридор РИ-414"],
    direction: Side.RIGHT,
    points: [325, 625, 325, 700],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-414",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-414", "РИ-419", "Коридор РИ-417", "Коридор РИ-419"],
    direction: Side.RIGHT,
    points: [325, 700, 325, 775],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-419",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-419", "РИ-416", "Коридор РИ-414", "Коридор РИ-416"],
    direction: Side.RIGHT,
    points: [325, 775, 325, 800],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-416",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-416", "РИ-418", "Коридор РИ-419", "Коридор РИ-418"],
    direction: Side.RIGHT,
    points: [325, 800, 325, 875],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-418",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-421", "РИ-418", "Коридор РИ-416", "Коридор РИ-421"],
    direction: Side.RIGHT,
    points: [325, 875, 325, 925],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-421",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-421", "РИ-420", "Коридор РИ-418", "Коридор РИ-420"],
    direction: Side.RIGHT,
    points: [325, 925, 325, 950],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-420",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-420",
      "РИ-423",
      "Тех-помещение",
      "Коридор РИ-421",
      "Коридор РИ-423",
    ],
    direction: Side.RIGHT,
    points: [325, 950, 325, 1025],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-423",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-423",
      "Тех-помещение",
      "РИ-422",
      "Коридор РИ-420",
      "Коридор РИ-422",
    ],
    direction: Side.RIGHT,
    points: [325, 1025, 325, 1075],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-422",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-422",
      "РИ-425",
      "Лестница 2",
      "Коридор РИ-423",
      "Коридор РИ-425",
    ],
    direction: Side.RIGHT,
    points: [325, 1075, 325, 1125],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-425",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-425",
      "Лестница 2",
      "РИ-425а",
      "Коридор РИ-422",
      "turnoverLeftToMain",
    ],
    direction: Side.RIGHT,
    points: [325, 1125, 325, 1225],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "turnoverLeftToMain",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["РИ-425а", "Коридор РИ-425"],
    direction: Side.RIGHT,
    points: [325, 1225, 325, 1300],
    section: "leftWing4",
    floor: 4,
    linkedSection: ["mainSection4"],
  },
  {
    id: "turnoverMainToLeft",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-427", "Коридор РадиоТочка", "РадиоТочка"],
    direction: Side.RIGHT,
    points: [325, 1300, 330, 1375],
    section: "mainSection4",
    floor: 4,
    linkedSection: ["leftWing4"],
  },
  {
    id: "Коридор РИ-427г",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-427г", "РИ-427в", "РИ-429б", "РИ-429", "Коридор РИ-429"],
    direction: Side.RIGHT,
    points: [125, 1375, 165, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-429",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-427а", "РИ-429", "Коридор РИ-427г", "Коридор РИ-427а"],
    direction: Side.RIGHT,
    points: [165, 1375, 195, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-427а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-427а", "РИ-427", "Коридор РИ-429", "Коридор РИ-427"],
    direction: Side.RIGHT,
    points: [195, 1375, 275, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-427",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-427",
      "РадиоТочка",
      "turnoverMainToLeft",
      "Коридор РадиоТочка",
      "Коридор РИ-427а",
    ],
    direction: Side.RIGHT,
    points: [275, 1375, 330, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РадиоТочка",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РадиоТочка",
      "РИ-424а",
      "turnoverMainToLeft",
      "Коридор РИ-427",
      "Коридор РИ-424а",
    ],
    direction: Side.RIGHT,
    points: [330, 1375, 385, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-424а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-424а", "С/у", "Коридор РадиоТочка", "Коридор С/у"],
    direction: Side.RIGHT,
    points: [385, 1375, 445, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор С/у",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["С/у", "Коридор РИ-424а", "Коридор РИ-424", "Коридор Буфет"],
    direction: Side.RIGHT,
    points: [445, 1375, 495, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-424",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-424", "Коридор С/у", "Коридор Буфет", "Коридор РИ-426"],
    direction: Side.RIGHT,
    points: [495, 1345, 495, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-426",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-424", "РИ-426", "Коридор РИ-424", "Коридор РИ-428"],
    direction: Side.RIGHT,
    points: [495, 1345, 545, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-428",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-426", "РИ-428", "Коридор РИ-426", "Коридор РИ-430"],
    direction: Side.RIGHT,
    points: [545, 1345, 595, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-430",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-428", "РИ-430", "Коридор РИ-428", "Коридор РИ-432"],
    direction: Side.RIGHT,
    points: [595, 1345, 645, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-432",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-430", "РИ-432", "Коридор РИ-430", "Коридор РИ-434"],
    direction: Side.RIGHT,
    points: [645, 1345, 695, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-434",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-432", "РИ-434", "Коридор РИ-432", "Коридор РИ-436"],
    direction: Side.RIGHT,
    points: [695, 1345, 745, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-436",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-434", "РИ-436", "Коридор РИ-434", "Коридор РИ-438"],
    direction: Side.RIGHT,
    points: [745, 1345, 855, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-438",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-436", "РИ-438", "Коридор РИ-436", "Коридор РИ-438 направо"],
    direction: Side.RIGHT,
    points: [855, 1345, 1025, 1345],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор Лестница Слева",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор гардероб налево",
      "Лестница Слева",
      "Буфет",
      "Коридор Буфет",
    ],
    direction: Side.RIGHT,
    points: [495, 1390, 495, 1450],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор Буфет",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор С/у",
      "Коридор РИ-424",
      "Коридор Лестница Слева",
      "Буфет",
    ],
    direction: Side.RIGHT,
    points: [495, 1375, 495, 1390],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор гардероб налево",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Гардероб",
      "Коридор Лестница Слева",
      "Лестница Слева",
      "Коридор гардероб направо",
      "Коридор вход наверх",
    ],
    direction: Side.RIGHT,
    points: [495, 1450, 770, 1450],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор гардероб направо",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Гардероб",
      "Коридор Лестница Справа",
      "Лестница Справа",
      "Коридор гардероб налево",
      "Коридор вход наверх",
    ],
    direction: Side.RIGHT,
    points: [770, 1450, 1085, 1450],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор вход наверх",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Вход",
      "Коридор гардероб налево",
      "Гардероб",
      "Коридор гардероб направо",
    ],
    direction: Side.RIGHT,
    points: [770, 1450, 770, 1475],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор Лестница Справа",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор гардероб направо",
      "Лестница Справа",
      "turnoverMainToRight",
      "Коридор РИ-438 направо",
    ],
    direction: Side.RIGHT,
    points: [1085, 1450, 1085, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "Коридор РИ-438 направо",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-438",
      "Коридор РИ-438",
      "Коридор Лестница Справа",
      "turnoverMainToRight",
    ],
    direction: Side.RIGHT,
    points: [1025, 1345, 1085, 1375],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "turnoverMainToRight",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-438 направо", "Коридор Лестница Справа"],
    direction: Side.RIGHT,
    points: [1085, 1375, 1230, 1375],
    section: "mainSection4",
    floor: 4,
    linkedSection: ["rightWing4"],
  },
  {
    id: "turnoverRightToMain",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-437", "Коридор РИ-435"],
    direction: Side.RIGHT,
    points: [1230, 1375, 1305, 1375],
    section: "rightWing4",
    floor: 4,
    linkedSection: ["mainSection4"],
  },
  {
    id: "Коридор РИ-445",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-446", "РИ-445", "Коридор РИ-446"],
    direction: Side.RIGHT,
    points: [1305, 875, 1305, 925],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-446",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-446", "РИ-443", "Коридор РИ-445", "Коридор РИ-443"],
    direction: Side.RIGHT,
    points: [1305, 925, 1305, 975],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-443",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-443", "РИ-444", "Коридор РИ-446", "Коридор РИ-444"],
    direction: Side.RIGHT,
    points: [1305, 975, 1305, 1050],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-444",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-441", "РИ-444", "Коридор РИ-443", "Коридор РИ-441"],
    direction: Side.RIGHT,
    points: [1305, 1050, 1305, 1100],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-441",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-441", "РИ-442", "Коридор РИ-444", "Коридор РИ-442"],
    direction: Side.RIGHT,
    points: [1305, 1100, 1305, 1125],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-442",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-440",
      "РИ-439",
      "РИ-442",
      "Коридор РИ-441",
      "Коридор РИ-440",
    ],
    direction: Side.RIGHT,
    points: [1305, 1125, 1305, 1200],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-440",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-440",
      "РИ-439",
      "РИ-437",
      "Коридор РИ-442",
      "Коридор РИ-437",
    ],
    direction: Side.RIGHT,
    points: [1305, 1200, 1305, 1300],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-437",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-437",
      "turnoverRightToMain",
      "Коридор РИ-438а",
      "Коридор РИ-440",
    ],
    direction: Side.RIGHT,
    points: [1305, 1300, 1305, 1375],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-438а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-438а", "РИ-437", "Коридор РИ-440", "Коридор РИ-437"],
    direction: Side.RIGHT,
    points: [1255, 1300, 1305, 1300],
    section: "rightWing4",
    floor: 4,
  },
  {
    id: "Коридор РИ-435",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-435", "turnoverRightToMain", "Коридор РИ-437"],
    direction: Side.RIGHT,
    points: [1305, 1375, 1305, 1425],
    section: "rightWing4",
    floor: 4,
  },
]

export const wallsFourth = [
  { x: 300, y: 0, width: 50, height: 0, floor: 4 },
  { x: 350, y: 1150, width: 0, height: 100, floor: 4 },
  { x: 470, y: 1500, width: 700, height: 0, floor: 4 },
  { x: 1230, y: 1500, width: 100, height: 0, floor: 4 },
  { x: 1280, y: 850, width: 50, height: 0, floor: 4 },
]

export const configSectionsGraphFourth: TGraph[] = [
  {
    id: "leftWing4",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["mainSection4"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "leftWing4",
    floor: 4,
  },
  {
    id: "mainSection4",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["leftWing4", "rightWing4"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "mainSection4",
    floor: 4,
  },
  {
    id: "rightWing4",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["mainSection4"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "rightWing4",
    floor: 4,
  },
]

export const auditoriumsConfigFourth = [
  ...leftWing,
  ...mainSection,
  ...rightWing,
]
