import { TAuditorium } from "../../entities/auditorium/model/interface"
import { Side } from "../../shared/model/geometry"
import { GraphDestination, TGraph } from "../../entities/graph/model/interface"

const leftWing3: TAuditorium[] = [
  {
    name: "РИ-301",
    height: 40,
    width: 100,
    coords: { x: 200, y: 0 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-301"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-301",
  },
  {
    name: "Лестница",
    height: 70,
    width: 100,
    coords: { x: 350, y: 0 },
    entry: Side.LEFT,
    linkedAuditoriums: [
      { floor: 4, id: "Лестница 4floor" },
      { floor: 2, id: "Лестница 2floor" },
      { floor: 1, id: "Лестница 1floor" },
    ],
    neighbors: ["Коридор Лестница 3floor", "Коридор РИ-301"],
    floor: 3,
    destination: GraphDestination.LADDER,
    section: "leftWing3",
    id: "Лестница 3floor",
  },

  {
    name: "РИ-302",
    height: 130,
    width: 100,
    coords: { x: 350, y: 70 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-302", "Коридор РИ-303а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 50,
    id: "РИ-302",
  },
  {
    name: "РИ-303",
    height: 50,
    width: 100,
    coords: { x: 200, y: 40 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-303", "Коридор Лестница 3floor"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-303",
  },
  {
    name: "РИ-303а",
    height: 110,
    width: 100,
    coords: { x: 200, y: 90 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-303а", "Коридор РИ-303"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -40,
    id: "РИ-303а",
  },
  {
    name: "РИ-304",
    height: 100,
    width: 100,
    coords: { x: 350, y: 200 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-305", "Коридор РИ-304"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 30,
    id: "РИ-304",
  },
  {
    name: "РИ-305",
    height: 200,
    width: 100,
    coords: { x: 200, y: 200 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-302", "Коридор РИ-305"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -60,
    id: "РИ-305",
  },
  {
    name: "РИ-306",
    height: 150,
    width: 100,
    coords: { x: 350, y: 300 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-309", "Коридор РИ-306"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 60,
    id: "РИ-306",
  },
  {
    name: "РИ-308",
    height: 100,
    width: 100,
    coords: { x: 350, y: 450 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-309а", "Коридор РИ-308"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 30,
    id: "РИ-308",
  },
  {
    name: "РИ-309",
    height: 50,
    width: 100,
    coords: { x: 200, y: 400 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-307", "Коридор РИ-309"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -10,
    id: "РИ-309",
  },
  {
    name: "РИ-309а",
    height: 100,
    width: 100,
    coords: { x: 200, y: 450 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-306", "Коридор РИ-309а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -30,
    id: "РИ-309а",
  },
  {
    // На плане входа нет, так что его с соседями не соединяем
    name: "РИ-310",
    height: 50,
    width: 100,
    coords: { x: 350, y: 550 },
    entry: Side.LEFT,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-310",
  },
  {
    name: "РИ-311",
    height: 50,
    width: 100,
    coords: { x: 200, y: 550 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-308", "Коридор РИ-311"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-311",
  },
  {
    name: "РИ-312",
    height: 50,
    width: 100,
    coords: { x: 350, y: 600 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-311", "Коридор РИ-312"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-312",
  },
  {
    name: "РИ-313",
    height: 150,
    width: 100,
    coords: { x: 200, y: 600 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-312", "Коридор РИ-313"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-313",
  },
  {
    name: "РИ-314а",
    height: 100,
    width: 100,
    coords: { x: 350, y: 650 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-313", "Коридор РИ-314а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-314а",
  },
  {
    name: "РИ-314",
    height: 50,
    width: 100,
    coords: { x: 350, y: 750 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-314а", "Коридор РИ-315", "РИ-315"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-314",
  },
  {
    name: "РИ-315",
    height: 100,
    width: 100,
    coords: { x: 200, y: 750 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-314а", "Коридор РИ-315", "РИ-314"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -25,
    id: "РИ-315",
  },
  {
    // Входа нет
    name: "РИ-316",
    height: 50,
    width: 100,
    coords: { x: 350, y: 800 },
    entry: Side.LEFT,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-316",
  },
  {
    name: "РИ-317",
    height: 100,
    width: 100,
    coords: { x: 200, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-318", "Коридор РИ-317"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 30,
    id: "РИ-317",
  },
  {
    name: "РИ-318",
    height: 100,
    width: 100,
    coords: { x: 350, y: 850 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-316", "Коридор РИ-318"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -30,
    id: "РИ-318",
  },
  {
    name: "РИ-319",
    height: 50,
    width: 100,
    coords: { x: 200, y: 950 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-317", "Коридор РИ-319"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-319",
  },
  {
    name: "РИ-320",
    height: 100,
    width: 100,
    coords: { x: 350, y: 950 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-319", "Коридор РИ-321", "РИ-321"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: 25,
    id: "РИ-320",
  },
  {
    name: "РИ-321",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-319", "Коридор РИ-321", "РИ-320"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-321",
  },
  {
    name: "РИ-322",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-321", "Коридор РИ-323", "РИ-323"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    id: "РИ-322",
  },
  {
    name: "РИ-323",
    height: 200,
    width: 100,
    coords: { x: 200, y: 1050 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-321", "Коридор РИ-323", "РИ-322"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "leftWing3",
    entryOffset: -75,
    id: "РИ-323",
  },
  {
    name: "Лестница 2",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1100 },
    entry: Side.LEFT,
    linkedAuditoriums: [
      { floor: 1, id: "Лестница 2 1floor" },
      { floor: 2, id: "Лестница 2 2floor" },
      { floor: 4, id: "Лестница 2 4floor" },
    ],
    neighbors: ["Коридор РИ-323", "Коридор Лестница 2 3floor"],
    floor: 3,
    destination: GraphDestination.LADDER,
    section: "leftWing3",
    id: "Лестница 2 3floor",
  },
]

const mainSection3: TAuditorium[] = [
  {
    name: "РИ-325",
    height: 250,
    width: 270,
    coords: { x: 30, y: 1250 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-325"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 110,
    id: "РИ-325",
  },
  {
    name: "?",
    height: 100,
    width: 70,
    coords: { x: 350, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.OTHER,
    section: "mainSection3",
    id: "hz1",
  },
  {
    name: "С/у",
    height: 100,
    width: 50,
    coords: { x: 420, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор Тайная", "Коридор С/у 3floor"],
    floor: 3,
    destination: GraphDestination.TOILET_MAN,
    section: "mainSection3",
    id: "С/у 3floor",
  },
  {
    name: "Лестница Слева",
    height: 100,
    width: 120,
    coords: { x: 350, y: 1400 },
    entry: Side.LEFT,
    linkedAuditoriums: [
      { floor: 1, id: "Лестница Слева 1floor" },
      { floor: 4, id: "Лестница Слева 4floor" },
      { floor: 2, id: "Лестница Слева 2floor" },
    ],
    neighbors: ["Коридор Лестница Слева 3floor", "Коридор РИ-325"],
    floor: 3,
    destination: GraphDestination.LADDER,
    section: "mainSection3",
    id: "Лестница Слева 3floor",
  },
  {
    name: "РИ-327",
    height: 100,
    width: 60,
    coords: { x: 470, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор С/у 3floor", "Коридор РИ-327"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 0,
    id: "РИ-327",
  },
  {
    name: "РИ-329",
    height: 100,
    width: 130,
    coords: { x: 530, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-327", "Коридор РИ-329"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: -50,
    id: "РИ-329",
  },
  {
    name: "РИ-331а",
    height: 100,
    width: 110,
    coords: { x: 660, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-326", "РИ-328", "Коридор РИ-328"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 30,
    id: "РИ-331а",
  },
  {
    name: "РИ-333",
    height: 100,
    width: 60,
    coords: { x: 770, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-328", "Коридор РИ-333"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    id: "РИ-333",
  },
  {
    name: "РИ-335",
    height: 100,
    width: 210,
    coords: { x: 830, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-334", "Коридор РИ-335"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: -60,
    id: "РИ-335",
  },
  {
    name: "РИ-337",
    height: 100,
    width: 70,
    coords: { x: 1040, y: 1400 },
    entry: Side.TOP,
    neighbors: ["Коридор РИ-330", "Коридор РИ-332", "РИ-332"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    id: "РИ-337",
  },
  {
    name: "РИ-324",
    height: 100,
    width: 150,
    coords: { x: 470, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-329", "Коридор РИ-324"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 40,
    id: "РИ-324",
  },
  {
    name: "РИ-326",
    height: 100,
    width: 100,
    coords: { x: 620, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-324", "Коридор РИ-326"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 20,
    id: "РИ-326",
  },
  {
    name: "РИ-328",
    height: 100,
    width: 50,
    coords: { x: 720, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-326", "Коридор РИ-328", "РИ-331а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    id: "РИ-328",
  },
  {
    name: "РИ-330",
    height: 100,
    width: 170,
    coords: { x: 770, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-333", "Коридор РИ-330", "РИ-335"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 20,
    id: "РИ-330",
  },
  {
    name: "РИ-332",
    height: 100,
    width: 170,
    coords: { x: 940, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-330", "Коридор РИ-332", "РИ-337"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "mainSection3",
    entryOffset: 50,
    id: "РИ-332",
  },
  {
    name: "Лестница Справа",
    height: 100,
    width: 120,
    coords: { x: 1110, y: 1400 },
    entry: Side.RIGHT,
    linkedAuditoriums: [
      { floor: 1, id: "Лестница Справа 1floor" },
      { floor: 2, id: "Лестница Справа 2floor" },
      { floor: 4, id: "Лестница Справа 4floor" },
    ],
    neighbors: ["Коридор Лестница Справа 3floor"],
    floor: 3,
    destination: GraphDestination.LADDER,
    section: "mainSection3",
    id: "Лестница Справа 3floor",
  },
  {
    name: "С/у (Ж)",
    height: 100,
    width: 50,
    coords: { x: 1110, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["Коридор РИ-332", "Коридор С/у (ж) 3floor"],
    floor: 3,
    destination: GraphDestination.TOILET_WOMAN,
    section: "mainSection3",
    id: "С/у (Ж) 3floor",
  },
  {
    name: "?",
    height: 100,
    width: 70,
    coords: { x: 1160, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.OTHER,
    section: "mainSection3",
    id: "hz2",
  },
  {
    name: "РИ-339",
    height: 250,
    width: 200,
    coords: { x: 1330, y: 1250 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-339", "Коридор РИ-341а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -110,
    id: "РИ-339",
  },
]

const rightWing3: TAuditorium[] = [
  {
    name: "РИ-334",
    height: 100,
    width: 60,
    coords: { x: 1220, y: 1150 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-341", "РИ-339а", "Коридор РИ-339а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -30,
    id: "РИ-334",
  },
  {
    name: "РИ-336",
    height: 100,
    width: 100,
    coords: { x: 1180, y: 1050 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-336", "Коридор РИ-338"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -20,
    id: "РИ-336",
  },
  {
    name: "?",
    height: 50,
    width: 100,
    coords: { x: 1330, y: 950 },
    entry: Side.LEFT,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.OTHER,
    section: "rightWing3",
    id: "hz3",
  },
  {
    name: "?",
    height: 50,
    width: 100,
    coords: { x: 1330, y: 900 },
    entry: Side.LEFT,
    neighbors: [],
    floor: 3,
    destination: GraphDestination.OTHER,
    section: "rightWing3",
    id: "hz4",
  },
  {
    name: "РИ-338",
    height: 50,
    width: 100,
    coords: { x: 1180, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-338", "Коридор РИ-340"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -15,
    id: "РИ-338",
  },
  {
    name: "РИ-340",
    height: 50,
    width: 100,
    coords: { x: 1180, y: 950 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-340", "hz3", "Коридор РИ-340а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    id: "РИ-340",
  },
  {
    name: "РИ-340а",
    height: 50,
    width: 100,
    coords: { x: 1180, y: 900 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-340а", "hz4", "Коридор РИ-343"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    id: "РИ-340а",
  },
  {
    name: "РИ-341",
    height: 150,
    width: 100,
    coords: { x: 1330, y: 1000 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-341", "Коридор РИ-336"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: 60,
    id: "РИ-341",
  },
  {
    name: "РИ-341а",
    height: 100,
    width: 60,
    coords: { x: 1330, y: 1150 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-341", "Коридор РИ-341а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -30,
    id: "РИ-341а",
  },
  {
    name: "РИ-342",
    height: 150,
    width: 100,
    coords: { x: 1180, y: 750 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-343", "Коридор РИ-345", "РИ-343"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: 60,
    id: "РИ-342",
  },
  {
    name: "РИ-342а",
    height: 100,
    width: 100,
    coords: { x: 1180, y: 650 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-342а", "Коридор РИ-344"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: -20,
    id: "РИ-342а",
  },
  {
    name: "РИ-343",
    height: 150,
    width: 100,
    coords: { x: 1330, y: 750 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-345", "Коридор РИ-343", "РИ-342"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: 60,
    id: "РИ-343",
  },
  {
    name: "РИ-344",
    height: 100,
    width: 100,
    coords: { x: 1180, y: 550 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-344", "Коридор Лестница 3 3floor"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: 10,
    id: "РИ-344",
  },
  {
    name: "РИ-345",
    height: 150,
    width: 100,
    coords: { x: 1330, y: 600 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-345", "Коридор РИ-342а"],
    floor: 3,
    destination: GraphDestination.AUDITORIUM,
    section: "rightWing3",
    entryOffset: 55,
    id: "РИ-345",
  },
  {
    name: "Лестница 3",
    height: 50,
    width: 100,
    coords: { x: 1330, y: 550 },
    entry: Side.LEFT,
    linkedAuditoriums: [
      { floor: 1, id: "Лестница 3 1floor" },
      { floor: 2, id: "Лестница 3 2floor" },
      { floor: 4, id: "Лестница 3 4floor" },
    ],
    neighbors: ["Коридор Лестница 3 3floor"],
    floor: 3,
    destination: GraphDestination.LADDER,
    section: "rightWing3",
    id: "Лестница 3 3floor",
  },
]
export const neighborsGraphThird: TGraph[] = [
  {
    id: "Коридор РИ-301",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Лестница 3floor", "РИ-301", "Коридор Лестница 3floor"],
    direction: Side.RIGHT,
    points: [325, 20, 325, 35],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор Лестница 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Лестница 3floor",
      "Коридор РИ-301",
      "РИ-303",
      "Коридор РИ-303",
    ],
    direction: Side.RIGHT,
    points: [325, 35, 325, 65],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-303",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-303а",
      "Коридор Лестница 3floor",
      "РИ-303",
      "Коридор РИ-303а",
    ],
    direction: Side.RIGHT,
    points: [325, 65, 325, 105],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-303а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-303а", "Коридор РИ-303", "РИ-302", "Коридор РИ-302"],
    direction: Side.RIGHT,
    points: [325, 105, 325, 185],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-302",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-305", "Коридор РИ-305", "РИ-302", "Коридор РИ-303а"],
    direction: Side.RIGHT,
    points: [325, 185, 325, 240],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-305",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-305", "Коридор РИ-302", "РИ-304", "Коридор РИ-304"],
    direction: Side.RIGHT,
    points: [325, 240, 325, 280],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-304",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-307", "Коридор РИ-307", "РИ-304", "Коридор РИ-305"],
    direction: Side.RIGHT,
    points: [325, 280, 325, 375],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-307",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-307", "Коридор РИ-304", "РИ-309", "Коридор РИ-309"],
    direction: Side.RIGHT,
    points: [325, 375, 325, 415],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-309",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-306", "Коридор РИ-307", "РИ-309", "Коридор РИ-306"],
    direction: Side.RIGHT,
    points: [325, 415, 325, 435],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-306",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-306", "Коридор РИ-309", "РИ-309а", "Коридор РИ-309а"],
    direction: Side.RIGHT,
    points: [325, 435, 325, 470],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-309а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-309а", "Коридор РИ-306", "РИ-308", "Коридор РИ-308"],
    direction: Side.RIGHT,
    points: [325, 470, 325, 530],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-308",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-311",
      "Коридор РИ-311",
      "РИ-308",
      "РИ-310",
      "Коридор РИ-309а",
    ],
    direction: Side.RIGHT,
    points: [325, 530, 325, 575],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-311",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-311",
      "Коридор РИ-312",
      "РИ-312",
      "РИ-310",
      "Коридор РИ-308",
    ],
    direction: Side.RIGHT,
    points: [325, 575, 325, 625],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-312",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-313", "Коридор РИ-311", "РИ-312", "Коридор РИ-313"],
    direction: Side.RIGHT,
    points: [325, 625, 325, 675],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-313",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-313", "Коридор РИ-312", "РИ-314а", "Коридор РИ-314а"],
    direction: Side.RIGHT,
    points: [325, 675, 325, 700],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-314а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-315",
      "РИ-314",
      "Коридор РИ-313",
      "РИ-314а",
      "Коридор РИ-315",
    ],
    direction: Side.RIGHT,
    points: [325, 700, 325, 775],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-315",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-315",
      "РИ-314",
      "Коридор РИ-314а",
      "РИ-316",
      "Коридор РИ-316",
    ],
    direction: Side.RIGHT,
    points: [325, 775, 325, 825],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-316",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-318", "Коридор РИ-315", "РИ-316", "Коридор РИ-318"],
    direction: Side.RIGHT,
    points: [325, 825, 325, 870],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-318",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-318", "Коридор РИ-317", "РИ-317", "Коридор РИ-316"],
    direction: Side.RIGHT,
    points: [325, 870, 325, 930],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-317",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-317", "Коридор РИ-318", "РИ-319", "Коридор РИ-319"],
    direction: Side.RIGHT,
    points: [325, 930, 325, 975],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-319",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-319",
      "Коридор РИ-317",
      "РИ-321",
      "РИ-320",
      "Коридор РИ-321",
    ],
    direction: Side.RIGHT,
    points: [325, 975, 325, 1025],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-321",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-322",
      "РИ-323",
      "Коридор РИ-319",
      "РИ-321",
      "РИ-320",
      "Коридор РИ-323",
    ],
    direction: Side.RIGHT,
    points: [325, 1025, 325, 1075],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-323",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-322",
      "РИ-323",
      "Коридор РИ-321",
      "Коридор Лестница 2 3floor",
      "Лестница 2 3floor",
    ],
    direction: Side.RIGHT,
    points: [325, 1075, 325, 1125],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "Коридор Лестница 2 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Лестница 2 3floor",
      "Коридор РИ-323",
      "Коридор Лестница 2 3floor",
      "turnoverLeft3ToMain3",
    ],
    direction: Side.RIGHT,
    points: [325, 1125, 325, 1200],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "turnoverLeft3ToMain3",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Коридор Лестница 2 3floor", "turnoverMain3ToLeft3"],
    direction: Side.RIGHT,
    points: [325, 1200, 325, 1300],
    section: "leftWing3",
    linkedSection: ["mainSection3"],
    floor: 3,
  },
  {
    id: "turnoverMain3ToLeft3",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор Лестница 2 3floor",
      "turnoverLeft3ToMain3",
      "Коридор Тайная Слева",
      "Коридор Лестница Слева 3floor",
    ],
    direction: Side.RIGHT,
    points: [325, 1300, 325, 1375],
    section: "mainSection3",
    linkedSection: ["leftWing3"],
    floor: 3,
  },
  {
    id: "Коридор Лестница Слева 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Лестница Слева 3floor",
      "turnoverMain3ToLeft3",
      "Коридор РИ-325",
      "Коридор Тайная Слева",
    ],
    direction: Side.RIGHT,
    points: [325, 1375, 325, 1450],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-325",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Лестница Слева", "РИ-325", "Коридор Лестница Слева"],
    direction: Side.RIGHT,
    points: [325, 1450, 325, 1485],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор Тайная Слева",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "turnoverMain3ToLeft3",
      "Коридор Лестница Слева 3floor",
      "Коридор Тайная",
      "hz1",
    ],
    direction: Side.RIGHT,
    points: [325, 1375, 385, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор Тайная",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор Тайная Слева",
      "С/у 3floor",
      "hz1",
      "Коридор С/у 3floor",
    ],
    direction: Side.RIGHT,
    points: [385, 1375, 445, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор С/у 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Коридор Тайная", "С/у 3floor", "РИ-327", "Коридор РИ-327"],
    direction: Side.RIGHT,
    points: [445, 1375, 500, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-327",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-329", "Коридор С/у 3floor", "РИ-327", "Коридор РИ-329"],
    direction: Side.RIGHT,
    points: [500, 1375, 545, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-329",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-329", "Коридор РИ-324", "РИ-324", "Коридор РИ-327"],
    direction: Side.RIGHT,
    points: [545, 1375, 585, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-324",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-326", "Коридор РИ-329", "РИ-324", "Коридор РИ-326"],
    direction: Side.RIGHT,
    points: [585, 1375, 690, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-326",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-326",
      "Коридор РИ-328",
      "РИ-328",
      "РИ-331а",
      "РИ-326",
      "Коридор РИ-324",
    ],
    direction: Side.RIGHT,
    points: [690, 1375, 745, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-328",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-333",
      "Коридор РИ-326",
      "РИ-331а",
      "РИ-328",
      "Коридор РИ-333",
    ],
    direction: Side.RIGHT,
    points: [745, 1375, 800, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-333",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор РИ-330",
      "РИ-330",
      "РИ-333",
      "РИ-335",
      "Коридор РИ-328",
    ],
    direction: Side.RIGHT,
    points: [800, 1375, 875, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-330",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-332",
      "РИ-337",
      "Коридор РИ-333",
      "РИ-330",
      "РИ-335",
      "Коридор РИ-332",
    ],
    direction: Side.RIGHT,
    points: [875, 1375, 1075, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор РИ-332",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-332",
      "РИ-337",
      "Коридор РИ-330",
      "Коридор РИ-330",
      "С/у (Ж) 3floor",
      "Коридор С/у (Ж) 3floor",
    ],
    direction: Side.RIGHT,
    points: [1075, 1375, 1135, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор С/у (Ж) 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["hz2", "Коридор Нарния", "С/у (Ж) 3floor", "Коридор РИ-332"],
    direction: Side.RIGHT,
    points: [1135, 1375, 1195, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор Нарния",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "hz2",
      "Коридор С/у (Ж) 3floor",
      "Коридор Лестница Справа 3floor",
      "TurnoverMain3ToRight3",
    ],
    direction: Side.RIGHT,
    points: [1195, 1375, 1305, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "Коридор Лестница Справа 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Лестница Справа 3floor",
      "Коридор Нарния",
      "TurnoverMain3ToRight3",
    ],
    direction: Side.RIGHT,
    points: [1255, 1450, 1305, 1375],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "TurnoverMain3ToRight3",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор Лестница Справа 3floor", "Коридор Нарния"],
    direction: Side.RIGHT,
    points: [1305, 1375, 1305, 1350],
    section: "mainSection3",
    linkedSection: ["rightWing3"],
    floor: 3,
  },
  {
    id: "TurnoverRight3ToMain3",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-339"],
    direction: Side.RIGHT,
    points: [1305, 1350, 1305, 1325],
    section: "rightWing3",
    linkedSection: ["mainSection3"],
    floor: 3,
  },
  {
    id: "Коридор РИ-339",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Коридор РИ-341а", "РИ-339", "TurnoverRight3ToMain3"],
    direction: Side.RIGHT,
    points: [1305, 1325, 1305, 1265],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-341а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор РИ-341",
      "РИ-341а",
      "РИ-334",
      "РИ-339",
      "Коридор РИ-339",
    ],
    direction: Side.RIGHT,
    points: [1305, 1265, 1305, 1170],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-341",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-341",
      "РИ-341а",
      "РИ-334",
      "Коридор РИ-336",
      "Коридор РИ-341а",
    ],
    direction: Side.RIGHT,
    points: [1305, 1170, 1305, 1135],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-336",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-341", "РИ-336", "Коридор РИ-341", "Коридор РИ-338"],
    direction: Side.RIGHT,
    points: [1305, 1135, 1305, 1080],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-338",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-338", "РИ-336", "Коридор РИ-336", "Коридор РИ-340"],
    direction: Side.RIGHT,
    points: [1305, 1080, 1305, 1010],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-340",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-338", "РИ-340", "Коридор РИ-340а", "hz3", "Коридор РИ-338"],
    direction: Side.RIGHT,
    points: [1305, 1010, 1305, 975],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-340а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-340а",
      "РИ-340",
      "hz3",
      "hz4",
      "Коридор РИ-340",
      "Коридор РИ-343",
    ],
    direction: Side.RIGHT,
    points: [1305, 975, 1305, 925],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-343",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-340а",
      "РИ-342",
      "РИ-343",
      "hz4",
      "Коридор РИ-340а",
      "Коридор РИ-345",
    ],
    direction: Side.RIGHT,
    points: [1305, 925, 1305, 885],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-345",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-345",
      "РИ-343",
      "РИ-342",
      "Коридор РИ-342а",
      "Коридор РИ-343",
    ],
    direction: Side.RIGHT,
    points: [1305, 885, 1305, 730],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-342а",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-345", "РИ-342а", "Коридор РИ-345", "Коридор РИ-344"],
    direction: Side.RIGHT,
    points: [1305, 730, 1305, 680],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор РИ-344",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-344",
      "РИ-342а",
      "Коридор РИ-342а",
      "Коридор Лестница 3 3floor",
    ],
    direction: Side.RIGHT,
    points: [1305, 680, 1305, 610],
    section: "rightWing3",
    floor: 3,
  },
  {
    id: "Коридор Лестница 3 3floor",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-344", "Лестница 3 3floor", "Коридор РИ-344"],
    direction: Side.RIGHT,
    points: [1305, 610, 1305, 575],
    section: "rightWing3",
    floor: 3,
  },
]

export const wallsThird = [
  { x: 300, y: 0, width: 50, height: 0, floor: 3 },
  { x: 300, y: 1500, width: 50, height: 0, floor: 3 },
  { x: 350, y: 1150, width: 0, height: 100, floor: 3 },
  { x: 470, y: 1500, width: 700, height: 0, floor: 3 },
  { x: 1230, y: 1500, width: 100, height: 0, floor: 3 },
  { x: 1280, y: 550, width: 50, height: 0, floor: 3 },
]

export const configSectionsGraphThird: TGraph[] = [
  {
    id: "leftWing3",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["mainSection3"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "leftWing3",
    floor: 3,
  },
  {
    id: "mainSection3",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["rightWing3", "leftWing3"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "mainSection3",
    floor: 3,
  },
  {
    id: "rightWing3",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["mainSection3"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "rightWing3",
    floor: 3,
  },
]

export const auditoriumsConfigThird = [
  ...leftWing3,
  ...mainSection3,
  ...rightWing3,
]
