import { TAuditorium } from "../../entities/auditorium/model/interface"
import { Side } from "../../shared/model/geometry"
import { GraphDestination, TGraph } from "../../entities/graph/model/interface"

export const leftWing: TAuditorium[] = [
  {
    name: "РИ-101",
    height: 50,
    width: 100,
    coords: { x: 200, y: 0 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-101"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "Лестница",
    height: 70,
    width: 100,
    coords: { x: 350, y: 0 },
    entry: Side.LEFT,
    neighbors: ["Коридор Лестница", "Коридор РИ-101"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-102",
    height: 50,
    width: 100,
    coords: { x: 200, y: 50 },
    entry: Side.RIGHT,
    neighbors: ["Коридор Лестница", "Коридор РИ-102"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-103",
    height: 130,
    width: 100,
    coords: { x: 350, y: 70 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-103", "Коридор РИ-102"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-104",
    height: 100,
    width: 100,
    coords: { x: 200, y: 100 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-103", "Коридор РИ-104"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-105",
    height: 100,
    width: 100,
    coords: { x: 350, y: 200 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-104", "РИ-106", "Коридор РИ-105"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-106",
    height: 100,
    width: 100,
    coords: { x: 200, y: 200 },
    entry: Side.RIGHT,
    neighbors: ["РИ-105", "Коридор РИ-104", "Коридор РИ-105"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-107",
    height: 100,
    width: 100,
    coords: { x: 350, y: 300 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-105", "РИ-108", "Коридор РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-108",
    height: 100,
    width: 100,
    coords: { x: 200, y: 300 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107", "Коридор РИ-105", "Коридор РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-109",
    height: 100,
    width: 100,
    coords: { x: 350, y: 400 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-110", "Коридор РИ-109"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-110",
    height: 50,
    width: 100,
    coords: { x: 200, y: 400 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-107", "Коридор РИ-110"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-112",
    height: 50,
    width: 100,
    coords: { x: 200, y: 450 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-109", "Коридор РИ-112"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-113",
    height: 50,
    width: 100,
    coords: { x: 350, y: 500 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-112", "Коридор РИ-113", "РИ-114"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-114",
    height: 50,
    width: 100,
    coords: { x: 200, y: 500 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-112", "РИ-113", "Коридор РИ-113"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-115",
    height: 150,
    width: 100,
    coords: { x: 200, y: 550 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-115", "Коридор РИ-116"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-116",
    height: 100,
    width: 100,
    coords: { x: 350, y: 550 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-113", "Коридор РИ-116"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-117",
    height: 100,
    width: 100,
    coords: { x: 350, y: 650 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-115", "Коридор РИ-117"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-118",
    height: 150,
    width: 100,
    coords: { x: 200, y: 700 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-117", "Коридор РИ-118"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-119",
    height: 100,
    width: 100,
    coords: { x: 350, y: 750 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-118", "Коридор РИ-119"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-120",
    height: 150,
    width: 100,
    coords: { x: 200, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-121", "Коридор РИ-120"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-121",
    height: 50,
    width: 100,
    coords: { x: 350, y: 850 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-119", "Коридор РИ-121"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-122",
    height: 100,
    width: 100,
    coords: { x: 350, y: 900 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-120", "Коридор РИ-122"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-123",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-122", "Коридор РИ-123", "РИ-126"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-124",
    height: 150,
    width: 100,
    coords: { x: 200, y: 1050 },
    entry: Side.RIGHT,
    neighbors: ["Лестница 2", "Коридор РИ-124", "Коридор РИ-127"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-125",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1200 },
    entry: Side.RIGHT,
    neighbors: ["Коридор РИ-124", "turnoverLeftToMain"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-126",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1000 },
    entry: Side.LEFT,
    neighbors: ["РИ-123", "Коридор РИ-123", "Коридор РИ-122"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-127",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["Коридор РИ-123", "Коридор РИ-127"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "Лестница 2",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1100 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
]

const mainSection: TAuditorium[] = [
  {
    name: "РИ-128",
    height: 100,
    width: 110,
    coords: { x: 30, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 40,
  },
  {
    name: "РИ-129",
    height: 100,
    width: 110,
    coords: { x: 140, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-130",
    height: 50,
    width: 70,
    coords: { x: 30, y: 1350 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-131",
    height: 100,
    width: 50,
    coords: { x: 250, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-132",
    height: 100,
    width: 110,
    coords: { x: 30, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 40,
  },
  {
    name: "РИ-133",
    height: 100,
    width: 50,
    coords: { x: 140, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РадиоТочка",
    height: 100,
    width: 160,
    coords: { x: 190, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 60,
  },
  {
    name: "РИ-134",
    height: 100,
    width: 70,
    coords: { x: 350, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-135",
    height: 100,
    width: 50,
    coords: { x: 420, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "Лестница Слева",
    height: 100,
    width: 120,
    coords: { x: 350, y: 1400 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-136",
    height: 70,
    width: 50,
    coords: { x: 470, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-137",
    height: 70,
    width: 50,
    coords: { x: 520, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-138",
    height: 70,
    width: 50,
    coords: { x: 570, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-139",
    height: 70,
    width: 50,
    coords: { x: 620, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-140",
    height: 70,
    width: 50,
    coords: { x: 670, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-141",
    height: 70,
    width: 50,
    coords: { x: 720, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-142",
    height: 70,
    width: 170,
    coords: { x: 770, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-143",
    height: 70,
    width: 170,
    coords: { x: 940, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "Гардероб",
    height: 70,
    width: 500,
    coords: { x: 520, y: 1355 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "Вход",
    height: 90,
    width: 350,
    coords: { x: 595, y: 1500 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "Лестница Справа",
    height: 100,
    width: 120,
    coords: { x: 1110, y: 1400 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-144",
    height: 100,
    width: 120,
    coords: { x: 1110, y: 1250 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-145",
    height: 150,
    width: 200,
    coords: { x: 1330, y: 1350 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-146",
    height: 100,
    width: 200,
    coords: { x: 1330, y: 1250 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
]

const rightWing: TAuditorium[] = [
  {
    name: "РИ-147",
    height: 100,
    width: 50,
    coords: { x: 1230, y: 1150 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-148",
    height: 100,
    width: 50,
    coords: { x: 1330, y: 1150 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-149",
    height: 50,
    width: 100,
    coords: { x: 1180, y: 1100 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-150",
    height: 100,
    width: 100,
    coords: { x: 1330, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-151",
    height: 100,
    width: 100,
    coords: { x: 1180, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-152",
    height: 150,
    width: 100,
    coords: { x: 1180, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-153",
    height: 150,
    width: 100,
    coords: { x: 1330, y: 900 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
  {
    name: "РИ-154",
    height: 50,
    width: 100,
    coords: { x: 1330, y: 850 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "rightWing1",
  },
]
export const neighborsGraph: TGraph[] = [
  {
    id: "Коридор РИ-101",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-101", "Лестница", "Коридор Лестница"],
    direction: Side.RIGHT,
    points: [325, 25, 325, 35],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор Лестница",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-102", "Лестница", "Коридор РИ-101", "Коридор РИ-102"],
    direction: Side.RIGHT,
    points: [325, 35, 325, 75],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-102",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-102", "РИ-103", "Коридор Лестница", "Коридор РИ-103"],
    direction: Side.RIGHT,
    points: [325, 75, 325, 135],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-103",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-103", "РИ-104", "Коридор РИ-102", "Коридор РИ-104"],
    direction: Side.RIGHT,
    points: [325, 135, 325, 150],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-104",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-104",
      "РИ-105",
      "РИ-106",
      "Коридор РИ-103",
      "Коридор РИ-105",
    ],
    direction: Side.RIGHT,
    points: [325, 150, 325, 250],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-105",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-105",
      "РИ-106",
      "РИ-107",
      "РИ-108",
      "Коридор РИ-104",
      "Коридор РИ-107",
    ],
    direction: Side.RIGHT,
    points: [325, 250, 325, 350],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-107",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-107",
      "РИ-108",
      "РИ-110",
      "Коридор РИ-105",
      "Коридор РИ-110",
    ],
    direction: Side.RIGHT,
    points: [325, 350, 325, 425],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-110",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-110", "РИ-109", "Коридор РИ-107", "Коридор РИ-109"],
    direction: Side.RIGHT,
    points: [325, 425, 325, 450],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-109",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-109", "РИ-112", "Коридор РИ-110", "Коридор РИ-112"],
    direction: Side.RIGHT,
    points: [325, 450, 325, 475],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-112",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-112",
      "РИ-113",
      "РИ-114",
      "Коридор РИ-109",
      "Коридор РИ-113",
    ],
    direction: Side.RIGHT,
    points: [325, 475, 325, 525],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-113",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-113",
      "РИ-114",
      "РИ-116",
      "Коридор РИ-112",
      "Коридор РИ-116",
    ],
    direction: Side.RIGHT,
    points: [325, 525, 325, 600],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-116",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-116", "РИ-115", "Коридор РИ-113", "Коридор РИ-115"],
    direction: Side.RIGHT,
    points: [325, 600, 325, 625],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-115",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-115", "РИ-117", "Коридор РИ-116", "Коридор РИ-117"],
    direction: Side.RIGHT,
    points: [325, 625, 325, 700],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-117",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-117", "РИ-118", "Коридор РИ-115", "Коридор РИ-118"],
    direction: Side.RIGHT,
    points: [325, 700, 325, 775],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-118",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-118", "РИ-119", "Коридор РИ-117", "Коридор РИ-119"],
    direction: Side.RIGHT,
    points: [325, 775, 325, 800],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-119",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-119", "РИ-121", "Коридор РИ-118", "Коридор РИ-121"],
    direction: Side.RIGHT,
    points: [325, 800, 325, 875],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-121",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-121", "РИ-120", "Коридор РИ-119", "Коридор РИ-120"],
    direction: Side.RIGHT,
    points: [325, 875, 325, 925],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-120",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-120", "РИ-122", "Коридор РИ-121", "Коридор РИ-122"],
    direction: Side.RIGHT,
    points: [325, 925, 325, 950],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-122",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-122",
      "РИ-123",
      "РИ-126",
      "Коридор РИ-120",
      "Коридор РИ-123",
    ],
    direction: Side.RIGHT,
    points: [325, 950, 325, 1025],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-123",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-123",
      "РИ-126",
      "РИ-127",
      "Коридор РИ-122",
      "Коридор РИ-127",
    ],
    direction: Side.RIGHT,
    points: [325, 1025, 325, 1075],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-127",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-127",
      "РИ-124",
      "Лестница 2",
      "Коридор РИ-123",
      "Коридор РИ-124",
    ],
    direction: Side.RIGHT,
    points: [325, 1075, 325, 1125],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "Коридор РИ-124",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-124",
      "Лестница 2",
      "РИ-125",
      "Коридор РИ-127",
      "turnoverLeftToMain",
    ],
    direction: Side.RIGHT,
    points: [325, 1125, 325, 1225],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "turnoverLeftToMain",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["РИ-125", "Коридор РИ-124"],
    direction: Side.RIGHT,
    points: [325, 1225, 325, 1300],
    section: "left_wing",
    floor: 1,
    linkedSection: ["main_section"],
  },
  {
    id: "turnoverMainToLeft",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-131", "Коридор РадиоТочка", "РадиоТочка"],
    direction: Side.RIGHT,
    points: [325, 1300, 330, 1375],
    section: "main_section",
    floor: 1,
    linkedSection: ["left_wing"],
  },
  {
    id: "Коридор РИ-130",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-130", "РИ-128", "РИ-132", "РИ-133", "Коридор РИ-133"],
    direction: Side.RIGHT,
    points: [125, 1375, 165, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-133",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-129", "РИ-132", "Коридор РИ-130", "Коридор РИ-129"],
    direction: Side.RIGHT,
    points: [165, 1375, 195, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-129",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-129", "РИ-131", "Коридор РИ-133", "Коридор РИ-131"],
    direction: Side.RIGHT,
    points: [195, 1375, 275, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-131",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-131",
      "РадиоТочка",
      "turnoverMainToLeft",
      "Коридор РадиоТочка",
    ],
    direction: Side.RIGHT,
    points: [275, 1375, 330, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РадиоТочка",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РадиоТочка",
      "РИ-134",
      "turnoverMainToLeft",
      "Коридор РИ-131",
      "Коридор РИ-134",
    ],
    direction: Side.RIGHT,
    points: [330, 1375, 385, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-134",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-134", "РИ-135", "Коридор РадиоТочка"],
    direction: Side.RIGHT,
    points: [385, 1375, 445, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-135",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-135",
      "Коридор РИ-134",
      "Коридор РИ-136",
      "Коридор Лестница Слева",
    ],
    direction: Side.RIGHT,
    points: [445, 1375, 495, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-136",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-136", "Коридор РИ-135", "Коридор Лестница Слева"],
    direction: Side.RIGHT,
    points: [495, 1345, 495, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-137",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-136", "РИ-137", "Коридор РИ-136", "Коридор РИ-138"],
    direction: Side.RIGHT,
    points: [495, 1345, 545, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-138",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-137", "РИ-138", "Коридор РИ-137", "Коридор РИ-139"],
    direction: Side.RIGHT,
    points: [545, 1345, 595, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-139",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-138", "РИ-139", "Коридор РИ-138", "Коридор РИ-140"],
    direction: Side.RIGHT,
    points: [595, 1345, 645, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-140",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-139", "РИ-140", "Коридор РИ-139", "Коридор РИ-141"],
    direction: Side.RIGHT,
    points: [645, 1345, 695, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-141",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-140", "РИ-141", "Коридор РИ-140", "Коридор РИ-142"],
    direction: Side.RIGHT,
    points: [695, 1345, 745, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-142",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-141", "РИ-142", "Коридор РИ-141", "Коридор РИ-143"],
    direction: Side.RIGHT,
    points: [745, 1345, 855, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-143",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-142", "РИ-143", "Коридор РИ-142"],
    direction: Side.RIGHT,
    points: [855, 1345, 1025, 1345],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор Лестница Слева",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-136",
      "Коридор РИ-135",
      "Коридор РИ-136",
      "Коридор гардероб налево",
    ],
    direction: Side.RIGHT,
    points: [495, 1375, 495, 1450],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор гардероб налево",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["Гардероб", "Коридор Лестница Слева", "Лестница Слева"],
    direction: Side.RIGHT,
    points: [495, 1450, 770, 1450],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор гардероб направо",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Гардероб",
      "Коридор Лестница Справа",
      "Лестница Справа",
      "Коридор гардероб налево",
      "Коридор вход наверх",
    ],
    direction: Side.RIGHT,
    points: [770, 1450, 1085, 1450],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор вход наверх",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["вход", "Коридор гардероб налево", "Гардероб"],
    direction: Side.RIGHT,
    points: [770, 1450, 770, 1475],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор Лестница Справа",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "Коридор гардероб направо",
      "Лестница Справа",
      "turnoverMainToRight",
    ],
    direction: Side.RIGHT,
    points: [1085, 1450, 1085, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "Коридор РИ-143 направо",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-143",
      "Коридор РИ-143",
      "Коридор Лестница Справа",
      "turnoverMainToRight",
    ],
    direction: Side.RIGHT,
    points: [1025, 1345, 1085, 1375],
    section: "main_section",
    floor: 1,
  },
  {
    id: "turnoverMainToRight",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-143 направо", "Коридор Лестница Справа"],
    direction: Side.RIGHT,
    points: [1085, 1375, 1230, 1375],
    section: "main_section",
    floor: 1,
    linkedSection: ["rightWing1"],
  },
  {
    id: "turnoverRightToMain",
    destination: GraphDestination.TURN_OVER,
    height: 0,
    neighbors: ["Коридор РИ-146", "Коридор РИ-145"],
    direction: Side.RIGHT,
    points: [1230, 1375, 1305, 1375],
    section: "rightWing1",
    floor: 1,
    linkedSection: ["main_section"],
  },
  {
    id: "Коридор РИ-154",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-152", "РИ-154", "Коридор РИ-152"],
    direction: Side.RIGHT,
    points: [1305, 875, 1305, 925],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-152",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-152", "РИ-153", "Коридор РИ-154", "Коридор РИ-153"],
    direction: Side.RIGHT,
    points: [1305, 925, 1305, 975],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-153",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-153", "РИ-151", "Коридор РИ-152", "Коридор РИ-151"],
    direction: Side.RIGHT,
    points: [1305, 975, 1305, 1050],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-151",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-150", "РИ-151", "Коридор РИ-153", "Коридор РИ-150"],
    direction: Side.RIGHT,
    points: [1305, 1050, 1305, 1100],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-150",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-150", "РИ-149", "Коридор РИ-151", "Коридор РИ-149"],
    direction: Side.RIGHT,
    points: [1305, 1100, 1305, 1125],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-149",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-147",
      "РИ-148",
      "РИ-149",
      "Коридор РИ-150",
      "Коридор РИ-147",
    ],
    direction: Side.RIGHT,
    points: [1305, 1125, 1305, 1200],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-147",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: [
      "РИ-147",
      "РИ-148",
      "РИ-146",
      "Коридор РИ-149",
      "Коридор РИ-146",
    ],
    direction: Side.RIGHT,
    points: [1305, 1200, 1305, 1300],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-146",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-146", "turnoverRightToMain", "Коридор РИ-144"],
    direction: Side.RIGHT,
    points: [1305, 1300, 1305, 1375],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-144",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-144", "РИ-146", "Коридор РИ-147", "Коридор РИ-146"],
    direction: Side.RIGHT,
    points: [1255, 1300, 1305, 1300],
    section: "rightWing1",
    floor: 1,
  },
  {
    id: "Коридор РИ-145",
    destination: GraphDestination.CORRIDOR,
    height: 0,
    neighbors: ["РИ-145", "turnoverRightToMain", "Коридор РИ-146"],
    direction: Side.RIGHT,
    points: [1305, 1375, 1305, 1425],
    section: "rightWing1",
    floor: 1,
  },
]
export const auditoriumsConfig = [...leftWing, ...mainSection, ...rightWing]

export const walls = [
  { x: 300, y: 0, width: 50, height: 0 },
  { x: 350, y: 1150, width: 0, height: 100 },
  { x: 470, y: 1500, width: 700, height: 0 },
  { x: 1230, y: 1500, width: 100, height: 0 },
  { x: 1280, y: 850, width: 50, height: 0 },
]

export const configSectionsGraph: TGraph[] = [
  {
    id: "left_wing",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["main_section"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "left_wing",
    floor: 1,
  },
  {
    id: "main_section",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["left_wing", "rightWing1"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "main_section",
    floor: 1,
  },
  {
    id: "rightWing1",
    destination: GraphDestination.SECTION,
    height: 0,
    neighbors: ["main_section"],
    direction: Side.RIGHT,
    points: [0, 0, 0, 0],
    section: "rightWing1",
    floor: 1,
  },
]
