import { TAuditorium } from "../../entities/auditorium/model/interface"
import { Side } from "../../shared/model/geometry"

export const leftWing: TAuditorium[] = [
  {
    name: "РИ-101",
    height: 50,
    width: 100,
    coords: { x: 200, y: 0 },
    entry: Side.RIGHT,
    neighbors: ["Лестница", "Корридор РИ-101"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "Лестница",
    height: 70,
    width: 100,
    coords: { x: 350, y: 0 },
    entry: Side.LEFT,
    neighbors: [],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-102",
    height: 50,
    width: 100,
    coords: { x: 200, y: 50 },
    entry: Side.RIGHT,
    neighbors: ["РИ-103"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-103",
    height: 130,
    width: 100,
    coords: { x: 350, y: 70 },
    entry: Side.LEFT,
    neighbors: ["РИ-102"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-104",
    height: 100,
    width: 100,
    coords: { x: 200, y: 100 },
    entry: Side.RIGHT,
    neighbors: ["РИ-103"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-105",
    height: 100,
    width: 100,
    coords: { x: 350, y: 200 },
    entry: Side.LEFT,
    neighbors: ["РИ-102"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-106",
    height: 100,
    width: 100,
    coords: { x: 200, y: 200 },
    entry: Side.RIGHT,
    neighbors: ["РИ-103"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-107",
    height: 100,
    width: 100,
    coords: { x: 350, y: 300 },
    entry: Side.LEFT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-108",
    height: 100,
    width: 100,
    coords: { x: 200, y: 300 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-109",
    height: 100,
    width: 100,
    coords: { x: 350, y: 400 },
    entry: Side.LEFT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-110",
    height: 50,
    width: 100,
    coords: { x: 200, y: 400 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-112",
    height: 50,
    width: 100,
    coords: { x: 200, y: 450 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-113",
    height: 50,
    width: 100,
    coords: { x: 350, y: 500 },
    entry: Side.LEFT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-114",
    height: 50,
    width: 100,
    coords: { x: 200, y: 500 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-115",
    height: 150,
    width: 100,
    coords: { x: 200, y: 550 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-116",
    height: 100,
    width: 100,
    coords: { x: 350, y: 550 },
    entry: Side.LEFT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-117",
    height: 100,
    width: 100,
    coords: { x: 350, y: 650 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-118",
    height: 150,
    width: 100,
    coords: { x: 200, y: 700 },
    entry: Side.RIGHT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-119",
    height: 100,
    width: 100,
    coords: { x: 350, y: 750 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-120",
    height: 150,
    width: 100,
    coords: { x: 200, y: 850 },
    entry: Side.RIGHT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-121",
    height: 50,
    width: 100,
    coords: { x: 350, y: 850 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-122",
    height: 100,
    width: 100,
    coords: { x: 350, y: 900 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-123",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1000 },
    entry: Side.RIGHT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-124",
    height: 150,
    width: 100,
    coords: { x: 200, y: 1050 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-125",
    height: 50,
    width: 100,
    coords: { x: 200, y: 1200 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-126",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1000 },
    entry: Side.LEFT,
    neighbors: ["РИ-108"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "РИ-127",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1050 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
  {
    name: "Лестница 2",
    height: 50,
    width: 100,
    coords: { x: 350, y: 1100 },
    entry: Side.LEFT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "left_wing",
  },
]

const mainSection: TAuditorium[] = [
  {
    name: "РИ-128",
    height: 100,
    width: 110,
    coords: { x: 30, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 40,
  },
  {
    name: "РИ-129",
    height: 100,
    width: 110,
    coords: { x: 140, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-130",
    height: 50,
    width: 70,
    coords: { x: 30, y: 1350 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-131",
    height: 100,
    width: 50,
    coords: { x: 250, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-132",
    height: 100,
    width: 110,
    coords: { x: 30, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 40,
  },
  {
    name: "РИ-133",
    height: 100,
    width: 50,
    coords: { x: 140, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РадиоТочка",
    height: 100,
    width: 160,
    coords: { x: 190, y: 1400 },
    entry: Side.TOP,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
    entryOffset: 60,
  },
  {
    name: "РИ-134",
    height: 100,
    width: 70,
    coords: { x: 350, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "РИ-135",
    height: 100,
    width: 50,
    coords: { x: 420, y: 1250 },
    entry: Side.BOTTOM,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
  {
    name: "Лестница Слева",
    height: 100,
    width: 120,
    coords: { x: 350, y: 1400 },
    entry: Side.RIGHT,
    neighbors: ["РИ-107"],
    floor: 1,
    section: "main_section",
  },
]

export const auditoriumsConfig = [...leftWing, ...mainSection]
